jargon = [
           'Assessment',
           'Bandwidth',
           'Benchmark',
           'Best practice',
           'Best practice methodology',
           'Bottle neck',
           'Change',
           'Coach/Couch the idea',
           'Compensation actions',
           'Competitive advantage',
           'Conflict resolution',
           'Constraints',
           'Core competencies',
           'Core values',
           'Cracker jack',
           'Critical thinker',
           'Cutting edge practices',
           'Dashboard',
           'Deliverable/s',
           'Diagnosis',
           'Downsize',
           'Enterprise',
           'Excellence',
           'Flavor of the month',
           'Fire fighter',
           'Game changer',
           'Game theory',
           'Gatekeeper',
           'Golden handshake',
           'Golden parachute',
           'Governance',
           'Headhunter',
           'Income pressures',
           'Individual contributor',
           'Leadership',
           'Learning experience',
           'Line of sight',
           'Low-hanging fruit',
           'Mad as a hornet',
           'Mastery',
           'Matrix organization',
           'Metrics Milestones',
           'Momentum',
           'Moving target',
           'Not invented here',
           'Initiative',
           'Individual contributor',
           'Outcomes',
           'Paradigm shift',
           'Partnership',
           'Positive Momentum',
           'Practical application',
           'Process',
           'Process management',
           'Recommendation',
           'Requirements',
           'Revenue growth',
           'Revenue mix',
           'Rightsize',
           'Seat at the table',
           'Show case',
           'Six sigma',
           'Silo',
           'Stakeholders',
           'Standards',
           'State of the art',
           'Superior (advantage|performance)',
           'Supply chain',
           'Synergy',
           'System',
           'Teamwork',
           'Thought leader',
           'Touchpoints',
           'Value added',
           'Womb to tomb',
           'Action',
           'Attract',
           'Baked In',
           'Boil the Ocean',
           'Call out',
           'Capture',
           'Champion',
           'Circle Back',
           'Circle the Wagons',
           'Collaborative',
           'Connect the dots',
           'Deliver',
           'Dialogue',
           'Differentiate',
           'Drill Down',
           'Drink the Kool Aid',
           'Emerg(e|ing)',
           'Enhance',
           'Evolve',
           'Execute',
           'Exploit',
           'Facilitate',
           'Forge',
           'Foster',
           'Generate',
           'Grow',
           'Highlight',
           'Implement',
           'Incentivize',
           'Ideate',
           'Impact',
           'Inspire',
           'Integrate',
           'Intervene',
           'Leverage',
           'Manage',
           'Mature Onboarding',
           'Partner',
           'Ping',
           'Re-engineer',
           'Reach out',
           'Simplify',
           'Spearhead',
           'Stratic',
           'Strategic plan',
           'Strategize',
           'Synergize',
           'Synergy',
           'Table that',
           'Tackle',
           'Think outside the box',
           'Throw a curve',
           'Touch base',
           'Transform',
           'Unify',
           'Utilise',
           'Vet',
           'Actionable',
           'Authored',
           'Customer-centric',
           'Dynamic',
           'Innovative',
           'Geographically dispersed',
           'Granular',
           'Holistic',
           'Nimble',
           'Results-driven',
           'Revolutionary',
           'Robust',
           'Scalable',
           'Seamless',
           'Superior',
           'Sustainable',
           'Thoughtful',
           'User-centric',
           'Win-win -Impactfully',
           'Synergistically'
         ]

# Feeling depressed?
#
# cheer me up - A little pick me up
module.exports = (robot) ->
  robot.hear /roflscale/i, (msg) ->
    buinessCat msg

businessCat = (msg) ->
  msg
    .http('http://imgur.com/gallery/top.json?q=business%20cat')
      .get() (err, res, body) ->
        images = JSON.parse(body)
        images = images.gallery
        image  = msg.random images
        msg.send "http://i.imgur.com/#{image.hash}#{image.ext}"

